# Generated by Django 4.2.7 on 2025-08-01 04:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EchoMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('client_address', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
